---
kind: Service
apiVersion: v1
metadata:
  name: trial-nodejs
spec:
  type: NodePort
  selector:
    app: trial-nodejs
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial-nodejs
spec:
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: trial-nodejs
  template:
    metadata:
      labels:
        app: trial-nodejs
    spec:
      containers:
      - name: nginx
        image: doandk/trial-nodejs:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
